import mysql.connector
f = mysql.connector.connect(host = "localhost", user = "root", passwd = "")
mycur = f.cursor()
mycur.execute("create database Hacktst;")
print("database created")
mycur.execute("use Hacktst;")
que = "create table trial(sno tinyint NOT NULL primary key, name varchar(30), section varchar(30));"
mycur.execute(que)
print("table created")
sn = int(input("enter sno"))
nam = input("enter name")
sec = input("enter section")
mycur.execute("insert into trial(sno, name, section)values({},'{}','{}')".format(sn, nam, sec))
print("values inserted")
f.commit()
mycur.execute("select * from trial;")
data = mycur.fetchall()
print(data)
mycur.close()
f.close()